name: BUILD_WORKFLOW

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      cache-key: ${{ steps.cache-deps.outputs.cache-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache Node.js modules
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps

      - name: List files in workspace
        run: ls -R

      - name: Create config.ts
        run: |
          echo "export const API_BASE_URL = '${{ secrets.API_BASE_URL }}';" > src/config.ts
          echo "export const WS_URL = '${{ secrets.WS_URL }}';" >> src/config.ts

      - name: Upload workspace as artifact
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: ./

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Restore Node.js modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Restore Node.js modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Test
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Restore Node.js modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Build
        run: npm run build
